07 post api art comm
lanc2112b/be-nc-news pull request #6
Opened 2023-02-21 17:10 UTC by lanc2112b

Implement post comment api endpoint ticket 07.

2023-02-22 08:47 UTC, yalicee requested changes
Please consider error handling for your post request ticket. there will be multiple 400 and 404s to test for

2023-02-22 08:47 UTC, yalicee commented on __tests__/app.test.js
> +        .expect(200)
expect 201 not 200

2023-02-22 08:47 UTC, yalicee commented on controllers/commentController.js
> +      response.status(200).send({ comment: result[0] }); // respond with the newly inserted row.
status 201 instead of 200

2023-02-22 10:45 UTC, emilyb93 commented on __tests__/app.test.js
> +
This test is a great test for the happy path but we are giving the user lots of input here and so we need to expect that the user can mess it up in many ways.
Think about the following issues and how you would handle them;
- client posts a comment to an article that doesnt exist
- client posts a comment to an article id that is not a number
- client does a post requests to a valid article but forgets to send the comment
- client posts a comment but the username doesn't exist in your database

Write the tests for these and see if you can figure out how to handle them :)

2023-02-22 10:47 UTC, emilyb93 commented on __tests__/app.test.js
> +            body: expect.any(String),
I disagree with some of this, if we are posting a comment, we know EXACTLY the details of some of this. We know that the author and body is what we sent, we know what article id it was posted to. The votes will be set by default to 0. We could even test the comment_id if we know how many comments are in the test data.

2023-02-22 10:47 UTC, emilyb93 requested changes
Good code but we need more tests to prove it

2023-02-22 10:49 UTC, yalicee requested changes

2023-02-22 10:49 UTC, yalicee commented on __tests__/app.test.js
> +    });
the comment you post will be the comment you get back. have a think about what you can expect

2023-02-23 10:33 UTC, yalicee approved these changes
Looks good :)

2023-02-23 10:33 UTC, yalicee commented on __tests__/app.test.js
> +  /* Ok Beth's bad url is breaking everything, or at least my handling of it is! */
remove this comment

2023-02-23 10:33 UTC, yalicee commented on controllers/commentController.js
> +      response.status(201).send({ comment: result[0] }); // respond with the newly inserted row.
For better code, result[0] could just be result and you would make sure to send the correct data back from your model

2023-02-23 10:33 UTC, yalicee commented on models/commentModel.js
> +  if (!body) {
remove log comments or any unnecessary comments

2023-02-23 11:12 UTC, merged